version: '3.8'

services:
  plex-auth-proxy:
    build: .
    container_name: plex-auth-proxy
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./config:/app/config:ro
      - ./logs:/app/logs
    environment:
      - NODE_ENV=production
      - CONFIG_PATH=/app/config/config.yaml
      - TZ=America/Chicago